# Generated by Django 3.1.2 on 2021-06-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
        migrations.AddField(
            model_name='message',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
