# Generated by Django 3.1.2 on 2021-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210515_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='default.png', null=True, upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='default.png', null=True, upload_to='product_pics'),
        ),
    ]
